apiVersion: composition.krateo.io/v1-0-1
kind: ApplicationGroup
metadata:
  name: test-01
spec:
  AppConfig:
    namespace: asd-asd
    username: asd-asd
    password: asd-asd
    urlapplicativo: qualcosa
    appVersion: v25.0.0
  Base:
    ProjectID: sigemi-prod
