apiVersion: composition.krateo.io/v10-0-0
kind: ApplicationGroup
metadata:
  name: application-group-02
  namespace: demo-system
spec:
  AppConfig:
    namespace: asd-asd
    username: asd-asd
    password: asd-asd
    urlapplicativo: qualcosa
    appVersion: v25.0.0
  Base:
    ProjectID: sigemi
