apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Release.Name }}-mutating-webhook
  namespace: {{ .Values.namespace }}
webhooks:
  - name: mutate.example.com
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    clientConfig:
      service:
        name: {{ .Release.Name }}-webhook
        namespace: {{ .Values.namespace }}
        path: /mutate
