apiVersion: v1
kind: Pod
metadata:
  name: shell-script-pod
  labels:
    app: shell-demo
spec:
  containers:
  - name: shell-container
    image: ubuntu:22.04
    command: ["/bin/bash", "-c"]
    args:
    - |
      #!/bin/bash
      # --- This is a sample shell script ---
      # The script demonstrates basic operations
      
      echo "Starting shell script execution..."
      
      # --- Configuration section ---
      APP_NAME="demo-app"
      VERSION="1.0.0"
      
      echo "Application: $APP_NAME"
      echo "Version: $VERSION"
      
      # --- Main processing loop ---
      for i in {1..5}; do
        echo "Iteration $i"
        sleep 2
      done
      
      # --- Cleanup and exit ---
      echo "Script completed successfully"
      
      # Keep container running for inspection
      tail -f /dev/null
  restartPolicy: Never